// Auto-generated feminine form lookup for gender-pair words
var FEMININE = {
  "abattu,e": "abattu, abattue",
  "abondant,e": "abondant, abondante",
  "absent,e": "absent, absente",
  "absolu,e": "absolu, absolue",
  "abstrait,e": "abstrait, abstraite",
  "acteur,trice": "acteur, actrice",
  "actif,ve": "actif, active",
  "actuel,le": "actuel, actuelle",
  "adroit,e": "adroit, adroite",
  "aérien,ne": "aérien, aérienne",
  "affreux,se": "affreux, affreuse",
  "âgé,e": "âgé, âgée",
  "aigu,ë": "aigu, aiguë",
  "aîné,e": "aîné, aînée",
  "algérien,ne": "algérien, algérienne",
  "américain,e": "américain, américaine",
  "ami,e": "ami, amie",
  "amoureux,se": "amoureux, amoureuse",
  "ancien,ne": "ancien, ancienne",
  "anglais,e": "anglais, anglaise",
  "annuel,le": "annuel, annuelle",
  "approprié,e": "approprié, appropriée",
  "arrogant,e": "arrogant, arrogante",
  "assidu,e": "assidu, assidue",
  "assis,e": "assis, assise",
  "attentif,ve": "attentif, attentive",
  "aucun,e": "aucun, aucune",
  "avocat,e": "avocat, avocate",
  "bas,se": "bas, basse",
  "beau,bel,belle": "beau, belle",
  "blanc,blanche": "blanc, blanche",
  "bleu,e": "bleu, bleue",
  "blond,e": "blond, blonde",
  "bon,bonne": "bon, bonne",
  "boulanger,ère": "boulanger, boulangère",
  "bref,brève": "bref, brève",
  "brillant,e": "brillant, brillante",
  "brun,e": "brun, brune",
  "canadien,ne": "canadien, canadienne",
  "candidat,e": "candidat, candidate",
  "ce,cette,ces": "ce, ces",
  "celle,celui": "celle, celui",
  "certain,e": "certain, certaine",
  "chacun,e": "chacun, chacune",
  "chat,te": "chat, chatte",
  "chaud,e": "chaud, chaude",
  "cher,chère": "cher, chère",
  "chinois,e": "chinois, chinoise",
  "chrétien,ne": "chrétien, chrétienne",
  "citoyen,ne": "citoyen, citoyenne",
  "clair,e": "clair, claire",
  "client,e": "client, cliente",
  "commun,e": "commun, commune",
  "compétent,e": "compétent, compétente",
  "complet,ète": "complet, complète",
  "concret,ète": "concret, concrète",
  "contemporain,e": "contemporain, contemporaine",
  "content,e": "content, contente",
  "copain,copine": "copain, copine",
  "correct,e": "correct, correcte",
  "courant,e": "courant, courante",
  "court,e": "court, courte",
  "créateur, -trice": "créateur, créatrice",
  "créatif, -ive": "créatif, créative",
  "creux, creuse": "creux, creuse",
  "criard, -e": "criard, criarde",
  "criminel, -le": "criminel, criminelle",
  "croyant, -e": "croyant, croyante",
  "crucial, -e": "crucial, cruciale",
  "cruel, -le": "cruel, cruelle",
  "cuisant, -e": "cuisant, cuisante",
  "cuisinier, -ère": "cuisinier, cuisinière",
  "cultivateur, -trice": "cultivateur, cultivatrice",
  "culturel, -le": "culturel, culturelle",
  "dangereux, -euse": "dangereux, dangereuse",
  "danois, -e": "danois, danoise",
  "danseur, -euse": "danseur, danseuse",
  "débordé, -e": "débordé, débordée",
  "débutant, -e": "débutant, débutante",
  "décisif, -ive": "décisif, décisiive",
  "déçu, -e": "déçu, déçue",
  "définitif, -ive": "définitif, définitiive",
  "défunt, -e": "défunt, défunte",
  "délicat, -e": "délicat, délicate",
  "délicieux, -euse": "délicieux, délicieuse",
  "dépourvu, -e": "dépourvu, dépourvue",
  "dernier, -ère": "dernier, dernière",
  "désolé, -e": "désolé, désolée",
  "dévoué, -e": "dévoué, dévouée",
  "différent, -e": "différent, différente",
  "direct, -e": "direct, directe",
  "directeur, -trice": "directeur, directrice",
  "distinct, -e": "distinct, distincte",
  "distrait, -e": "distrait, distraite",
  "divers, -e": "divers, diverse",
  "doux, douce": "doux, douce",
  "dur, -e": "dur, dure",
  "écolier, -ère": "écolier, écolière",
  "effectif, -ive": "effectif, effectiive",
  "égal, -e": "égal, égale",
  "élégant, -e": "élégant, élégante",
  "émotif, -ive": "émotif, émotiive",
  "employé, -e": "employé, employée",
  "employeur, -euse": "employeur, employeuse",
  "ému, -e": "ému, émue",
  "enrhumé, -e": "enrhumé, enrhumée",
  "enseignant, -e": "enseignant, enseignante",
  "entier, -ère": "entier, entière",
  "entraîneur, -euse": "entraîneur, entraîneuse",
  "envieux, -euse": "envieux, envieuse",
  "épais, -se": "épais, épaisse",
  "équivalent, -e": "équivalent, équivalente",
  "espion, -ne": "espion, espionne",
  "essentiel, -le": "essentiel, essentielle",
  "étendu, -e": "étendu, étendue",
  "éternel, -le": "éternel, éternelle",
  "étranger, -ère": "étranger, étrangère",
  "étroit, -e": "étroit, étroite",
  "étudiant, -e": "étudiant, étudiante",
  "éventuel, -le": "éventuel, éventuelle",
  "évident, -e": "évident, évidente",
  "exact, -e": "exact, exacte",
  "excellent, -e": "excellent, excellente",
  "exceptionnel, -le": "exceptionnel, exceptionnelle",
  "excessif, -ive": "excessif, excessiive",
  "exigeant, -e": "exigeant, exigeante",
  "expérimenté, -e": "expérimenté, expérimentée",
  "fameux, -euse": "fameux, fameuse",
  "familial, -e": "familial, familiale",
  "fatal, -e": "fatal, fatale",
  "fatigant, -e": "fatigant, fatigante",
  "faux, fausse": "faux, fausse",
  "favori, -te": "favori, favorite",
  "fécond, -e": "fécond, féconde",
  "féminin, -e": "féminin, féminine",
  "fermé, -e": "fermé, fermée",
  "ferré, -e": "ferré, ferrée",
  "fiancé, -e": "fiancé, fiancée",
  "fictif, -ive": "fictif, fictiive",
  "fier, fière": "fier, fière",
  "final, -e": "final, finale",
  "financier, -ère": "financier, financière",
  "fleuri, -e": "fleuri, fleurie",
  "foncé, -e": "foncé, foncée",
  "foncier, -ère": "foncier, foncière",
  "fondamental, -e": "fondamental, fondamentale",
  "formel, -le": "formel, formelle",
  "fort, -e": "fort, forte",
  "fou, folle": "fou, folle",
  "frais, fraîche": "frais, fraîche",
  "franc, franche": "franc, franche",
  "français, -e": "français, française",
  "fréquent, -e": "fréquent, fréquente",
  "frileux, -euse": "frileux, frileuse",
  "frit, -e": "frit, frite",
  "furieux, -euse": "furieux, furieuse",
  "gai, -e": "gai, gaie",
  "gardien, -ne": "gardien, gardienne",
  "géant, -e": "géant, géante",
  "gênant, -e": "gênant, gênante",
  "général, -e": "général, générale",
  "généreux, -euse": "généreux, généreuse",
  "génial, -e": "génial, géniale",
  "gentil, -le": "gentil, gentille",
  "glacial, -e": "glacial, glaciale",
  "glorieux, -euse": "glorieux, glorieuse",
  "gourmand, -e": "gourmand, gourmande",
  "gracieux, -euse": "gracieux, gracieuse",
  "grand, -e": "grand, grande",
  "gras, -se": "gras, grasse",
  "gratuit, -e": "gratuit, gratuite",
  "grec, grecque": "grec, grecque",
  "gris, -e": "gris, grise",
  "gros, -se": "gros, grosse",
  "grossier, -ère": "grossier, grossière",
  "habitant, -e": "habitant, habitante",
  "habituel, -le": "habituel, habituelle",
  "handicapé, -e": "handicapé, handicapée",
  "hardi, -e": "hardi, hardie",
  "haut, -e": "haut, haute",
  "héritier, -ère": "héritier, héritière",
  "heureux, -euse": "heureux, heureuse",
  "hollandais, -e": "hollandais, hollandaise",
  "honteux, -euse": "honteux, honteuse",
  "hospitalier, -ère": "hospitalier, hospitalière",
  "humain, -e": "humain, humaine",
  "idéal, -e": "idéal, idéale",
  "idiot, -e": "idiot, idiote",
  "illégal, -e": "illégal, illégale",
  "illimité, -e": "illimité, illimitée",
  "immédiat, -e": "immédiat, immédiate",
  "immigré, -e": "immigré, immigrée",
  "immobilier, -ère": "immobilier, immobilière",
  "impératif, -ive": "impératif, impératiive",
  "important, -e": "important, importante",
  "imprévu, -e": "imprévu, imprévue",
  "inattendu, -e": "inattendu, inattendue",
  "inclus, -e": "inclus, incluse",
  "inconnu, -e": "inconnu, inconnue",
  "indépendant, -e": "indépendant, indépendante",
  "indifférent, -e": "indifférent, indifférente",
  "individuel, -le": "individuel, individuelle",
  "inférieur, -e": "inférieur, inférieure",
  "informaticien, -ne": "informaticien, informaticienne",
  "innocent, -e": "innocent, innocente",
  "inquiet, -ète": "inquiet, inquiète",
  "insouciant, -e": "insouciant, insouciante",
  "insuffisant, -e": "insuffisant, insuffisante",
  "intelligent, -e": "intelligent, intelligente",
  "interdit, -e": "interdit, interdite",
  "intéressant, -e": "intéressant, intéressante",
  "intérieur, -e": "intérieur, intérieure",
  "international, -e": "international, internationale",
  "invité, -e": "invité, invitée",
  "irrégulier, -ère": "irrégulier, irrégulière",
  "issu, -e": "issu, issue",
  "jaloux, -ouse": "jaloux, jalouse",
  "jardinier, -ère": "jardinier, jardinière",
  "joli, -e": "joli, jolie",
  "joueur, -euse": "joueur, joueuse",
  "joyeux, -euse": "joyeux, joyeuse",
  "juif, juive": "juif, juive",
  "tel,le": "tel, telle",
  "thermal,e": "thermal, thermale",
  "total,e": "total, totale",
  "tout,e": "tout, toute",
  "traditionnel,le": "traditionnel, traditionnelle",
  "transparent,e": "transparent, transparente",
  "travailleur,se": "travailleur, travailleuse",
  "un,une": "un, une",
  "uni,e": "uni, unie",
  "universel,le": "universel, universelle",
  "urbain,e": "urbain, urbaine",
  "urgent,e": "urgent, urgente",
  "vert,e": "vert, verte",
  "veuf,ve": "veuf, veuve",
  "vieux,vieille": "vieux, vieille",
  "vigilant,e": "vigilant, vigilante",
  "violent,e": "violent, violente",
  "violet,te": "violet, violette",
  "visiteur,se": "visiteur, visiteuse",
  "vivant,e": "vivant, vivante",
  "voisin,e": "voisin, voisine",
  "vrai,e": "vrai, vraie",
  "alambiqué,e": "alambiqué, alambiquée",
  "alléchant,e": "alléchant, alléchante",
  "ambivalent,e": "ambivalent, ambivalente",
  "apprenti,e": "apprenti, apprentie",
  "assermenté,e": "assermenté, assermentée",
  "avisé,e": "avisé, avisée",
  "cadastral,e": "cadastral, cadastrale",
  "cardinal,e": "cardinal, cardinale",
  "charnel,le": "charnel, charnelle",
  "civilisé,e": "civilisé, civilisée",
  "clandestin,e": "clandestin, clandestine",
  "comédien,ne": "comédien, comédienne",
  "controversé,e": "controversé, controversée",
  "décousu,e": "décousu, décousue",
  "défectueux,se": "défectueux, défectueuse",
  "démodé,e": "démodé, démodée",
  "dépensier,ère": "dépensier, dépensière",
  "désabusé,e": "désabusé, désabusée",
  "draconien,ne": "draconien, draconienne",
  "édenté,e": "édenté, édentée",
  "émotionnel,le": "émotionnel, émotionnelle",
  "éolien,ne": "éolien, éolienne",
  "épicurien,ne": "épicurien, épicurienne",
  "estompé,e": "estompé, estompée",
  "expérimental,e": "expérimental, expérimentale",
  "exquis,e": "exquis, exquise",
  "fastidieux,se": "fastidieux, fastidieuse",
  "féodal,e": "féodal, féodale",
  "fictif,ve": "fictif, fictive",
  "harassant,e": "harassant, harassante",
  "improductif,ve": "improductif, improductive",
  "indifférencié,e": "indifférencié, indifférenciée",
  "insensé,e": "insensé, insensée",
};

function getPronounceText(french) {
  if (!french || !french.includes(",")) return french;
  if (FEMININE[french]) return FEMININE[french];
  return french;
}